services:
  django:
    build:
      context: ./backend
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # depends_on:
    #   - db
    networks:
      - app_network

  nextjs:
    build:
      context: ./frontend
    container_name: nextjs
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    networks:
      - app_network
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:8000

  # db:
  #   image: mysql:8
  #   container_name: db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "53306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

# volumes:
#   mysql_data: